version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
